parameters:
  ApplicationName: {{ stackGroup.project }}
  PublicSubnetId1:
    resolver: stack-output
    stack: /infra/vpc.yml
    output: PublicSubnet1Id
  PublicSubnetId2:
    resolver: stack-output
    stack: /infra/vpc.yml
    output: PublicSubnet2Id
  PublicSubnetId3:
    resolver: stack-output
    stack: /infra/vpc.yml
    output: PublicSubnet3Id
