project: sandbox-client-vpn
regions: eu-west-1
# Supported regions:
# eu-central-1 - Frankfurt
# eu-west-1 - Ireland
# eu-west-2 - London
# ap-southeast-1 - Singapore
# ap-southeast-2 - Sydney
# us-east-1 - N. Virginia
# us-east-2 - Ohio
# us-west-2 - Oregon

